name       : alpine
version    : 2.24
release    : 2
source     :
    - http://alpine.x10host.com/alpine/release/src/alpine-2.24.tar.xz : 651a9ffa0a29e2b646a0a6e0d5a2c8c50f27a07a26a61640b7c783d06d0abcef
license    : Apache-2.0
component  : network.mail
summary    : Console-based Email Client
description: |
    Alpine is a rewrite of the Pine Message System that adds support for Unicode and other features.
setup      : |
    %configure --with-passfile=".pine.passfile"
build      : |
    %make
install    : |
    %make_install
