name       : alpine
version    : '2.26'
release    : 7
source     :
    - https://alpineapp.email/alpine/release/src/alpine-2.26.tar.xz : c0779c2be6c47d30554854a3e14ef5e36539502b331068851329275898a9baba
license    : Apache-2.0
component  : network.mail
summary    : Console-based Email Client
description: |
    Alpine is a rewrite of the Pine Message System that adds support for Unicode and other features.
builddeps  :
    - pkgconfig(libxcrypt)
setup      : |
    # Reconfigure in order to not error out on runstatedir. This can probably be removed in a future release
    %reconfigure --with-passfile=".pine.passfile"
build      : |
    %make
install    : |
    %make_install
