name       : alpine
version    : '2.25'
release    : 4
source     :
    - http://alpine.x10host.com/alpine/release/src/alpine-2.25.tar.xz : 658a150982f6740bb4128e6dd81188eaa1212ca0bf689b83c2093bb518ecf776
license    : Apache-2.0
component  : network.mail
summary    : Console-based Email Client
description: |
    Alpine is a rewrite of the Pine Message System that adds support for Unicode and other features.
setup      : |
    %configure --with-passfile=".pine.passfile"
build      : |
    %make
install    : |
    %make_install
